version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres

  dbtalks:
    build: ./dbtalk
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/postgres

  metanews:
    build: ./metanews
    container_name: metanews
    ports:
      - '3000:3000'
    volumes:
      - ./metanews:/app
    stdin_open: true
    tty: true
    depends_on:
      - dbtalks
